### ISSUE TITLE
How to create SurvData for oncocast?

### ISSUE THREAD

**Issue by wonwon0317** [AxelitoMartin/OncoCast#38]
Hi,

I want to use oncocast using WES mutation calling data and copy number data.

Looking at SurvData uploaded as an example file, the column names were ImpCov1, Cov1. What does this mean, and how can I create it when using mutation data and copy numbers?

In the paper, MSK-IMPACT cancer panel was used, and it was said that it was performed with three versions of the gene. Are all about 400 genes used?

Generally, there are several mutations in one patient. In this case, it would be appreciated if you let us know how it was expressed in one line.

Thanks.

**Comment by AxelitoMartin** [comment]
Hi, 
Sorry for the delay.
I apologize if this is not clearly stated in the manual (and please let me know how to improve the wording for it).

The names of the columns correspond to the name of the features to be included in the run. For example say your WES data has mutations in the TP53 gene (as I assume it will if you are doing cancer related research), then one of the columns of the dataframe to input.
Each patient represents a line of the dataframe, and if a mutation was found for that patient in TP53 then that cell i,j will be annotated with a 1. Does that make more sense?

For the copy number data are you dealing with raw calls (ie: -2, -1, 0, 1, 2)? If so you should separate them from the mutation calls, with columns say call TP53.Del, TP53.Amp if you have deletions or amplifications on TP53 and repeat the process described above for mutations.

Along with that add your survival (time to event) columns, and use that as the input for OncoCast.
I actually also have a package that automatically annotates such matrices in a binary format gnomeR (https://github.com/AxelitoMartin/gnomeR) an will separate mutations from copy-number alterations for you. 

For the MSK IMPACT platform, this is not relevant for you in the context of WES. Basically IMPACT has 3 panels (that have grown over time adding more genes) and is something we add deal with in the paper. 

As per your last point, do you mean some patients had MULTIPLE mutations in the same gene (I feel that is a rare event but perhaps you have such cases if you are working with hypermutated samples)? If so there is no direct way to adjust for this in our setting but something I could propose so modified data processing code if that is of interest.

Please let me know if you have any other questions! And thanks for your interest in OncoCast!

**Comment by wonwon0317** [comment]
> Hi,
> Sorry for the delay.
> I apologize if this is not clearly stated in the manual (and please let me know how to improve the wording for it).
> 
> The names of the columns correspond to the name of the features to be included in the run. For example say your WES data has mutations in the TP53 gene (as I assume it will if you are doing cancer related research), then one of the columns of the dataframe to input.
> Each patient represents a line of the dataframe, and if a mutation was found for that patient in TP53 then that cell i,j will be annotated with a 1. Does that make more sense?
> 
> For the copy number data are you dealing with raw calls (ie: -2, -1, 0, 1, 2)? If so you should separate them from the mutation calls, with columns say call TP53.Del, TP53.Amp if you have deletions or amplifications on TP53 and repeat the process described above for mutations.
> 
> Along with that add your survival (time to event) columns, and use that as the input for OncoCast.
> I actually also have a package that automatically annotates such matrices in a binary format gnomeR (https://github.com/AxelitoMartin/gnomeR) an will separate mutations from copy-number alterations for you.
> 
> For the MSK IMPACT platform, this is not relevant for you in the context of WES. Basically IMPACT has 3 panels (that have grown over time adding more genes) and is something we add deal with in the paper.
> 
> As per your last point, do you mean some patients had MULTIPLE mutations in the same gene (I feel that is a rare event but perhaps you have such cases if you are working with hypermutated samples)? If so there is no direct way to adjust for this in our setting but something I could propose so modified data processing code if that is of interest.
> 
> Please let me know if you have any other questions! And thanks for your interest in OncoCast!

**Comment by wonwon0317** [comment]
Thank you for your detailed and kind answer!!

I solved the problem with your advice.

My last question,  it is correct to ask when multiple mutations occur in same gene.

If multiple mutations occur in an important gene, I think this could have a significant impact on survival. That's why it would be appreciated if you let me know how to handle the multiple mutation gene.

Thank you.

**Comment by AxelitoMartin** [comment]
No problem happy I was able to help.
So I never really thought about this, but you are correct there are reasons to believe that multiple mutations in an important regulatory gene may lead to greater issue when building the protein.
I think having 0 as wildtype, 1 as 1 mutation, 2 as 2 mutations (etc) is a bad idea because the effect of multiple mutations is probably not linear. I think a potential solution is to create columns that are unique to a given mutation for a gene that are often mutated multiple times:

Say patient X has multiple mutations in gene Y, create columns:

- Y_mut1 --> 0 wild type, 1 has that specific mutation
- Y_mut2 --> 0 wild type, 1 has that specific mutation
...

Do you see what I mean?

The main issue I could see with this however is you might end up with super sparse data and thus reduce signal. At the moment I don't have a better idea :/ but if you have some literature on how this was dealt with I am happy to go over it!

Hope this helps!
